### ISSUE TITLE
Forth tag (topics)

### ISSUE THREAD

**Issue by FForth** [nschulzke/LC3Forth#1]
Please create a "Forth" tag and ... for this project. (Label "Manage topic" in open project)

**Comment by nschulzke** [comment]
Closing. This repository just got spammed along with 290 others, and I have no intention of going along with that.

**Comment by nschulzke** [comment]
I'm reopening this because I reconsidered. This isn't an unfair request, even if it was done in a very spammy way.

@FForth, please note that you look like a single-purpose account whose sole purpose is to spam Forth repositories with a generic request to add a tag. Creating a new account and then reporting 290 issues with the same title and body in 290 different repositories over the course of a single day doesn't look very thoughtful. I'm going to give you the benefit of the doubt, and assume you're just a very enthusiastic Forth fan, but spamming like this rubs people wrong. Give at least some personalization so repo owners know you're human.

I will add the tag when I get a reply back that contains content that is unique to this repository.

**Comment by FForth** [comment]
Yes you are right. This is an attempt to fix a poorly functioning tag service (Fortn) on Github.
Next will be adding a code to my repository. 

P.S. Post translated Google translate. My English is poor. (native Russian).

**Comment by FForth** [comment]
Specially made also therefore  https://github.com/stars/ForthStar
